### ISSUE TITLE
EcoflowException: Server is too busy - Did the MQTT-API get limited in 2024-03?

### ISSUE THREAD

**Issue by Nid01** [bogdancs92/ecoflow-powerstream-nodejs#5]
I'm using ecoflow-powerstream-nodejs to balance the`output of my PowerStream so I don't feed more energy into the grid than I need, which gets calculated using a shelly EM3.
I had the required automation trigger every second to check if an adjustment of the output is needed.
This worked fine for months but since 2024-03-02, the API seems to be rate limited?
Now when I enable the automation, not every update of the output change gets through, so I have situations where I feed to more energy into the grid than needed.

When I reload the PowerStream device in Home Assistant, I get following the error in the log of Home Assistant.
```
Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 5:11:45 PM (3 occurrences)
Last logged: 5:15:47 PM

Error setting up entry PS for ecoflow_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/__init__.py", line 83, in async_setup_entry
    await hass.async_add_executor_job(auth.authorize)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 52, in authorize
    response = self.get_json_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 94, in get_json_response
    raise EcoflowException(f"{response_message}")
custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt.EcoflowException: (('Server is too busy',), {})
```

I'm not really looking for a solution, because this seems not to be an issue with project, but I'll note anything interesting on the development of the situation, until I get around switching to the other API of EcoFlow.

**Comment by marcuslib** [comment]
yeah mine is doing the same, i guess this is the reason, can the code please be amended to work.

If you are using MQTT to connect to the API be aware that only 10 unique client IDs are allowed per day. As such, it is suggested that you choose a static client_id for your application or integration to use consistently. If your code generates a unique client_id (as mine did) for each connection, you can exceed this limit very quickly when testing or debugging code.

**Comment by marcuslib** [comment]
i have modified setupMQTTConnection with 

const STATIC_CLIENT_ID = "YOUR_STATIC_CLIENT_ID"; // Replace "YOUR_STATIC_CLIENT_ID" with your desired static client ID

async function setupMQTTConnection(mqttDaten) {
    const options = {
        port: mqttDaten.Port,
        clientId: STATIC_CLIENT_ID, // Use the static client ID here
        username: mqttDaten.User,
        password: mqttDaten.Passwort,
        protocol: mqttDaten.protocol,
        rejectUnauthorized: false,
    };

    const client = await mqtt.connect("mqtt://" + mqttDaten.URL, options);
    client.mqttDaten = mqttDaten;

    client.on('close', () => {
        log("Ecoflow MQTT broker is deconnected");
    });

    client.on('error', function (error) {
        log('Error with the Ecoflow MQTT broker connection ' + error);
    });

    client.on('reconnect', function () {
        log('Reconnecting to Ecoflow MQTT broker...', mqttDaten.URL, mqttDaten.Port, mqttDaten.protocol); 
        client.end();
    });

    client.on('message', (topic, payload) => {
        log('Received Message to Ecoflow MQTT broker', topic, payload.toString()); 
    });

    return client;
}


and it seems to be working great again

**Comment by Nid01** [comment]
> yeah mine is doing the same, i guess this is the reason, can the code please be amended to work.
> 
> If you are using MQTT to connect to the API be aware that only 10 unique client IDs are allowed per day. As such, it is suggested that you choose a static client_id for your application or integration to use consistently. If your code generates a unique client_id (as mine did) for each connection, you can exceed this limit very quickly when testing or debugging code.

Thank you. I've seen the same information as you on Facebook: https://www.facebook.com/groups/1405868123482532/permalink/1606670410068968/.

I already switched to the new API from EcoFlow, which works with HTTP-Requests, so I call this issue as solved.
I don't think there is a point in further relaying on nodejs unless it enables stuff, which the other API does not support.

**Comment by giovanne123** [comment]
Only for your information: the new official API supports both http and mqtt. 
I use new API mqtt for receiving instand/live data I want to react on and http in parallel for set/get  calls.
I had with the official API with mqtt trouble with possible random clientids too. I am using static clientid now.

With the knowledge it is maybe worth to change in (old) nodejs solution too. I have it still running in parallel and will change it until I have migrated everything in my HA.

@marcuslib , thanks for the info about this limitation.

**Comment by marcuslib** [comment]
No problem @giovanne123 are you ok with sharing the code change once you have done it, I have not had a proper chance to look at it yet. thanks in advance,

@Nid01 I have not had a proper look at the new API stuff, have you got the HTTP requests working to update the demand, if so are you ok to share. thanks

**Comment by Nid01** [comment]
> No problem @giovanne123 are you ok with sharing the code change once you have done it, I have not had a proper chance to look at it yet. thanks in advance,
> 
> @Nid01 I have not had a proper look at the new API stuff, have you got the HTTP requests working to update the demand, if so are you ok to share. thanks

@svenerbe shared this https://github.com/tolwi/hassio-ecoflow-cloud/issues/124#issuecomment-1944125107 and it works fine for me in Home Assistant.
Currently I'm looking into the examples of @Mark-Hicks https://github.com/Mark-Hicks/ecoflow-api.

For MQTT I also need to read up on the details about the static clientId, because in hassio-ecoflow-cloud it is not used yet, which is not ideal?

**Comment by Mark-Hicks** [comment]
In general, and for Home Assistant in particular, it may be best to use MQTT for HA sensor updates as the device itself publishes those changes as they occur and your integration can simply subscribe and consume those updates. It is possible to use either HTTP or MQTT for settings changes but if an integration (like ecoflow-cloud, for example) is going to be based around MQTT then it makes sense, in my view, to have things like switches or selects both update based on MQTT data and publish changes to the corresponding settings on the ../set topics -- overall I think MQTT is superior to any sort of periodic polling and doing a query/response loop over HTTP every second does not seem optimal...

**Comment by Mark-Hicks** [comment]
With regard to using the ecoflow-cloud integration or any other similar integration or YAML package that utilizes the public MQTT server: This is an unsanctioned and reverse-engineered approach. In basic terms this functionality is achieved by "impersonating the app" which has been an iterative process as things change over time. I am not aware of any specific change made recently on the public MQTT server and suspect the error mentioned at the top of this thread may have just been a transient back-end issue. I have seen approaches that send an MQTT request for the state of all sensors every 1 or few seconds for example which results in a huge payload of response data. If enough people were running something like that it could cause issues. That may or may not be the case but I would certainly discourage taking that approach, especially when impersonating the app which only asks, once, for the comprehensive status of a given device, when the app for that device is first opened (to initially populate the state of all data fields in the app)...

The ecoflow-cloud integration opens a separate MQTT connection for each device using a unique client ID... This works on the public server as it would see it as several instances of the app running on separate devices but it would still be more optimal to open a single connection, subscribe to the topics for each device within an account, and then manage the updates, per device, based on data published to the relevant topics...

I am experimenting with the creation of an integration similar to ecoflow-cloud and possibly based on a fork of it but aimed at using the official API. It will need to be adapted to utilize a unique, but static, client_id and only a single connection using the MQTT credentials obtained via API keys. I will need to determine if a config_flow can be created that allows tracking of a single (or multiple) API key/secret pairs along with a sub-set of device name/sn pairs for each set of API keys. If that can only be done as a flat set of key/secret/name/sn data sets then the integration would need to include logic to determine which devices share API creds and act accordingly to use a single MQTT connection per API key with a client_id based on the unique login id for MQTT of that key...

**Comment by Nid01** [comment]
> I am experimenting with the creation of an integration similar to ecoflow-cloud and possibly based on a fork of it but aimed at using the official API. It will need to be adapted to utilize a unique, but static, client_id and only a single connection using the MQTT credentials obtained via API keys. I will need to determine if a config_flow can be created that allows tracking of a single (or multiple) API key/secret pairs along with a sub-set of device name/sn pairs for each set of API keys. If that can only be done as a flat set of key/secret/name/sn data sets then the integration would need to include logic to determine which devices share API creds and act accordingly to use a single MQTT connection per API key with a client_id based on the unique login id for MQTT of that key...

@Mark-Hicks 
I'm giving it a try, too: https://github.com/Nid01/core/tree/EcoFlow_IoT_Open/homeassistant/components/ecoflow_iot_open
So I'm trying to build on https://github.com/tolwi/hassio-ecoflow-cloud and on https://github.com/Nid01/core/tree/EcoFlow_IoT_Open/homeassistant/components/econet because for the beginning it seems like a well written component for getting to the point of receiving data and displaying it in home assistant.

Publishing changes for the device settings via MQTT would come next after that.

Figuring out, how to get the integration into hassio instead of homeassistant/core I'll have to figure out later.

**Comment by Mark-Hicks** [comment]
@Nid01 I have a modified version of ecoflow-cloud working with the API and using a static client ID
```
self.client_id = DOMAIN + "_" + auth.mqtt_username
```
The challenge now is finding a way to allow the user to add multiple devices (by SN) in the UI but have the integration use the same single MQTT connection (just subscribe to different topics and track the data and set/get topics per device)...

At present I'm looking at getting this to work with Smart Home Panel since that is not supported by ecoflow-cloud but it is a device included in the API...

**Comment by Nid01** [comment]
> The challenge now is finding a way to allow the user to add multiple devices (by SN) in the UI but have the integration use the same single MQTT connection (just subscribe to different topics and track the data and set/get topics per device)...

@Mark-Hicks 
Instead of adding the devices by SN in the UI, I plan to get all devices via HTTP-GET request https://api-e.ecoflow.com/iot-open/sign/device/list, checking, what devices I can support and subscribe to the topics in a way like it is done in the pyeconet EcoNetApiInterface:
```
    def _on_connect(self, client, userdata, flags, rc):
        _LOGGER.debug(f"Connected with result code: {str(rc)}")
        client.subscribe(f"user/{self._account_id}/device/reported")
        client.subscribe(f"user/{self._account_id}/device/desired")
```
Just using a list of devices with a loop. 🤔

**Comment by Mark-Hicks** [comment]
@Nid01 I considered that, however, I have a lot of devices in my account and don't necessarily want all of them. I think there needs to be some way for the user to specify which devices they want to turn on integration for. Also, it would be nice if there was a way to add multiple access/secret key pairs ("accounts") and then devices under each "account" with a separate MQTT connection opened for each... I'm not sure if/how that can be done within config_flow.py but I'm also fairly new to writing a full blown integration...

**Comment by Nid01** [comment]
@Mark-Hicks I'm using devices via the tasmota component of home assistant.
There it is no problem to remove devices, which have been discovered and created, when I don't want them in home assistant.

Alternatively it is maybe possible during setup with config_flow.py to list all available devices and there select only the devices, that should be integrated.

The third option would be to do it the same way as the ecoflow-cloud integration is doing it, by entering each individual device SN.

The usage case for adding multiple key pairs would only be valid for me, when you have registered your devices with different accounts in the EcoFlow app, but that would make the management of the devices in the app difficult.
For that you can share devices between multiple accounts in the app.

As fas as I understand using the EcoFlow IoT Open API you can't assign devices to specific key pairs, so also not to individual MQTT connections.
Of course you could create individual MQTT connections by generating multiple certificate data and subscribing to only one topic per device, but I don't they the value in creating multiple MQTT connections, when one is enough and it is not possible to assign devices to specific key pairs.
The key pairs just give you access to the EcoFlow account and the devices registered to and possibly shared with it.

**Comment by Mark-Hicks** [comment]
@Nid01 

The API does not currently allow access to shared devices but that is something I've asked them to add as I think there are plenty of good use cases for that. The key pair ties to the underlying EcoFlow account itself (email/pw setup in app) which contains all associated devices (by SN) and the MQTT credentials supplied for given key pair are always the same so, for a given EcoFlow account there is one login (Email/PW), one set of MQTT credentials (UserName/PW), and one set of API keys (at least that is all they allow at this point)...

If the key pair can be assigned one time within config flow and then each device added by SN I think that would be good enough though it might be more elegant to present a drop down of available/supported devices for the user to choose in the UI. But I'm not sure I understand, from the HA Dev Docs, how to ask for the account info (keys) separate from the device or how to refer to the account (keys) each time a new device is added (or if this approach is even possible via the UI).

The ecoflow cloud integration presents everything in a single form and then opens a separate MQTT connection for each device (to the same account), which is undesirable, and requires the user to enter the same account credentials for each new device as well. I've adapted this to utilize API keys and establish a static client_ID based on the MQTT creds supplied by the API, but it will take more involved re-work to code things around managing separate devices on the same MQTT connection...

Do you know if/how the config_flow might be setup to support configuration of an "account" and then adding multiple devices under that account using forms in the UI?

**Comment by Nid01** [comment]
> Do you know if/how the config_flow might be setup to support configuration of an "account" and then adding multiple devices under that account using forms in the UI?

@Mark-Hicks It's my first time getting deeper into programming so I'm just getting familiar with how HA works.
As soon as I stumble onto a solution for that, I'll let you know. 👍

**Comment by Mark-Hicks** [comment]
@Nid01 

I hear you. I've done a fair amount with complex YAML packages and done my own integrations that way and made some changes to a couple of custom integrations others have created but this is my first deep dive as well and I'm trying to avoid writing everything from scratch my first time out...

Happy to share my own discoveries as well.

**Comment by Mark-Hicks** [comment]
@Nid01 on a separate note I've run into a rather interesting and somewhat frustrating issue with SHP...

Unlike other devices, the SHP requires setting the charge and discharge limits in the same command/payload at the same time. If you specify one without the other the other gets set to a default value. In my YAML package I resolved this using a template that simply referenced the current state for "discharge limit" when the setting for "charge limit" was being changed (via number entity / slider) but how to do that in the entity definition escapes me. I thought perhaps using hass.states.get(entity).state to grab the current value of the opposite setting could work but there are a couple of challenges. The first is how to get the appropriate hass object passed through to where the entities are being defined (in order to reference it in a callable lambda) and the second is determining (not assuming) what the entitiy_id got set to for the opposite number entity...

To add insult to injury, the SHP also does not report the state of charge/discharge limits in the heartbeat. Instead it only reports that information on ../quotas, in a separate payload, when and if the value changes so you end up having to change one or the other in the app to populate the entity state in the first place. In my YAML package I resolved this by using an automation to watch for that payload and then republish it on a separate ../limits topic using the retain flag. But even then, you have to see it the first time out by changing something in the app...

I could make an HTML call to get the current value of both settings and use that function to return the necessary data to the lambda. In theory that same function could be used to seed the state of both entities after initial creation as well but I'm a bit lost as to how that would work... In many ways the YAML package (though tedious and much less elegant) was easier to work around these sorts of things...

**Comment by Nid01** [comment]
@Mark-Hicks 
At first glance for that situation to set both values, I would use a HTTP request to get both current values, too.
I have yet to get to the point of writing out the initial entity creation so I can see, if there are any obstacles in that.
