### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by lowrisk75** [bogdancs92/ecoflow-powerstream-nodejs#6]
Sorry, I'm out of topic but do you have a how to by anychance? I have no experience with node red but I'm dying to find a way to control it so I can do some automation with node red based on my Shelly PM sensor

**Comment by bogdancs92** [comment]
Hello, you can find some doc here 👍 
https://github.com/giovanne123/Ecoflow_Powerstream_HomeAssistant_Automation_Documentation/blob/main/README.md

**Comment by lowrisk75** [comment]
Thank you!
sorry for asking a silly question, but I'm a bit confused, where do we get theses values:
`NODE_ENV=development
KEY_URL=cmd
TOKEN=my_token
TOKEN_VAL=my_secret_for_token`
